language: node_js
services:
  - postgresql
dist: trusty
sudo: true
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_install:
  # Use default port
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  # Use 9.6 auth config:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo service postgresql restart
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add mocha
before_script:
  - psql -c "CREATE DATABASE \"DAW_test\";" -U postgres
  - psql -c "CREATE USER daw_test WITH PASSWORD '1234567890';" -U postgres
  #  - yarn add bcrypt #run if error in headers
cache:
  yarn: true
  directories:
    - "node_modules"
