language: node_js
services:
  - postgresql
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add mocha
before_script:
  - psql -c "CREATE DATABASE DAW_test;" -U postgres
  - psql -c "CREATE USER daw_test WITH PASSWORD '1234567890';" -U postgres
cache:
  yarn: true
  directories:
    - "node_modules"
